#!/bin/bash
ls -a1 | awk 'BEGIN {ORS=", "} {if ($0 == "." || $0 == "..") {print $0} else if (substr($0,1,1) ~ /[[:digit:]]/) {print $0} else if (substr($0,1,1) ~ /[[:alpha:]]/) {print $0} else {print "./"$0}} END {print ""}'

